version: '3.8'

services:
  pwa_frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - fronted
  pwa_backend:
    build:
      context: ./backend/service
    ports:
     - 3366:3366
    networks:
      - backend
      - fronted
  mongo_database:
    build:
      context: ./backend/database
    ports:
      - 27017:27017
    networks: 
      - backend

networks:
  backend:
    driver: bridge
  fronted:
    driver: bridge